#!/bin/bash
export CONFLUENT=7.5.1
export CONFLUENT_DOCKER_TAG=7.5.1
export CONFLUENT_SHORT=7.5
export CONFLUENT_PREVIOUS="7.5.0"
export CONFLUENT_RELEASE_TAG_OR_BRANCH=7.5.1-post
export CONFLUENT_MAJOR=7
export CONFLUENT_MINOR=5
export CONFLUENT_PATCH=1
export CP_VERSION_FULL="$CONFLUENT_MAJOR.$CONFLUENT_MINOR.$CONFLUENT_PATCH"
